version: '3.5'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    networks:
      - host-net
    ports:
      - "5432:5432"
    volumes:
      # provide correct path to volumes
      - /root/workspace/postgresql:/var/lib/postgresql
      - /root/workspace/postgresql_data:/var/lib/postgresql/data
      - /var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/16/bin
      - PGDATA=/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:latest
    container_name: sonar
    hostname: sonar
    restart: unless-stopped
    networks:
      - host-net
    ports:
      - "9000:9000"
    volumes:
      # provide correct path to volumes
      - /root/workspace/sonarqube_data:/opt/sonarqube/data
      - /root/workspace/sonarqube_extensions:/opt/sonarqube/extensions
      - /root/workspace/sonarqube_logs:/opt/sonarqube/logs
    env_file:
      - .env
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
      - PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - JAVA_HOME=/opt/java/openjdk
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
      - JAVA_VERSION=jdk-17.0.9+9
      - DOCKER_RUNNING=true
      - SONARQUBE_HOME=/opt/sonarqube
      - SONAR_VERSION=10.3.0.82913
      - SQ_DATA_DIR=/opt/sonarqube/data
      - SQ_EXTENSIONS_DIR=/opt/sonarqube/extensions
      - SQ_LOGS_DIR=/opt/sonarqube/logs
      - SQ_TEMP_DIR=/opt/sonarqube/temp
    working_dir: /opt/sonarqube

networks:
  host-net:
    external: true
