stages:
  - analysis
  - fetch_issues

variables:
  PROJECT_MAIN_BRANCH: "master" # Default branch name if not set elsewhere

analysis:
  stage: analysis
  script:
    - set -x
    - apt-get update -y
    - apt-get install -y openssh-client curl rsync jq
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - ssh-keyscan -H $REMOTE_SERVER >> ~/.ssh/known_hosts
    - export PROJECT_TEMP_NAME=$(openssl rand -hex 12)
    - 'echo "Project key: $PROJECT_TEMP_NAME"'
    - ssh $REMOTE_USER@$REMOTE_SERVER "mkdir -p $REMOTE_SERVER_TMP_DIR/$PROJECT_TEMP_NAME"
    - rsync -avz ./ $REMOTE_USER@$REMOTE_SERVER:$REMOTE_SERVER_TMP_DIR/$PROJECT_TEMP_NAME
    - echo "Code copied to $REMOTE_USER@$REMOTE_SERVER:$REMOTE_SERVER_TMP_DIR/$PROJECT_TEMP_NAME"
    - |
      REQUEST_BODY=$(cat <<EOF
      {
        "key": "$PROJECT_TEMP_NAME",
        "name": "$PROJECT_TEMP_NAME",
        "source": "$REMOTE_SERVER_TMP_DIR/$PROJECT_TEMP_NAME",
        "mainBranch": "$PROJECT_MAIN_BRANCH"
      }
      EOF
      )
      echo "Request Body: $REQUEST_BODY"
      ANALYSIS_RESPONSE=$(curl --connect-timeout 0 --max-time 0 -s -w "\n%{http_code}" -X POST "$REMOTE_SERVER_API_ADDRESS/scanner/scan/analysis" \
           -H "Content-Type: application/json" \
           -H "Authorization: $AUTH_TOKEN" \
           -d "$REQUEST_BODY")
      ANALYSIS_HTTP_STATUS=$(echo "$ANALYSIS_RESPONSE" | tail -n1)
      if [ "$ANALYSIS_HTTP_STATUS" -ne 200 ]; then
        echo "Request failed with status code $ANALYSIS_HTTP_STATUS"
        ssh $REMOTE_USER@$REMOTE_SERVER "rm -rf $REMOTE_SERVER_TMP_DIR/$PROJECT_TEMP_NAME"
        exit 1
      fi
      echo "Waiting for 15 seconds for SonarQube internal work"
      sleep 15
    - ssh $REMOTE_USER@$REMOTE_SERVER "rm -rf $REMOTE_SERVER_TMP_DIR/$PROJECT_TEMP_NAME"
    - echo "PROJECT_TEMP_NAME=$PROJECT_TEMP_NAME" > project_name.env
  artifacts:
    reports:
      dotenv: project_name.env 
  # Default branch name if not set elsewhere
  only:
    - master

fetch_issues:
  stage: fetch_issues
  needs:
    - job: analysis
      artifacts: true
  script:
    - set -x
    - 'echo "Project key: $PROJECT_TEMP_NAME"'
    - |
      ISSUES_RESPONSE=$(curl -s --connect-timeout 0 --max-time 0 -w "\n%{http_code}" -X GET "$REMOTE_SERVER_API_ADDRESS/scanner/issues/get-all-security-issues?name=$PROJECT_TEMP_NAME" \
        -H "Content-Type: application/json" \
        -H "Authorization: $AUTH_TOKEN")
    - ISSUES_HTTP_STATUS=$(echo "$ISSUES_RESPONSE" | tail -n1)
    - ISSUES_RESPONSE_BODY=$(echo "$ISSUES_RESPONSE" | sed '$ d')
    - |
      if [ "$ISSUES_HTTP_STATUS" -ne 200 ]; then
        echo "Request failed with status code $ISSUES_HTTP_STATUS"
        exit 1
      fi
    - |
      if [ "$ISSUES_RESPONSE_BODY" != "[]" ]; then
        echo "Warning! Find security issues"
        echo "$ISSUES_RESPONSE_BODY"
        echo "$ISSUES_RESPONSE_BODY" > issues_list.json
        echo "Issues saved to file issues_list.json"
        exit 2
      fi
  artifacts:
    paths:
      - issues_list.json
    when: always
  allow_failure:
    exit_codes: [2]
  only:
    - master
